import ts from 'typescript';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const output=ts.transpileModule(readFileSync(new URL('../src/runtimeState.ts',import.meta.url),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS}}).outputText;
const context={exports:{},Date};vm.runInNewContext(output,context);
const {reduceLive}=context.exports;
const event=(seq,kind,rest={})=>({provider:'codex',id:'a',seq,kind,...rest});
let view=reduceLive(undefined,event(1,'started'));
view=reduceLive(view,event(2,'delta',{text:'Olá',item_id:'m1'}));
view=reduceLive(view,event(3,'approval',{request_id:'7',tool:'Comando',detail:'test'}));
assert.equal(view.requests.length,1);
const restored=JSON.parse(JSON.stringify(view));
assert.equal(restored.text,'Olá');assert.equal(restored.requests[0].request_id,'7');
assert.equal(reduceLive(view,event(2,'delta',{text:'duplicado'})),view);
view=reduceLive(view,event(4,'resolved',{request_id:'7'}));
assert.equal(view.requests.length,0);
view=reduceLive(view,event(5,'delta',{text:'Resposta final',item_id:'m2'}));
assert.equal(view.text,'Resposta final','Different message items must not be concatenated');
view=reduceLive(view,event(6,'done',{error:'process exited'}));
assert.equal(view.busy,false);assert.equal(view.error,'process exited');
view=reduceLive(view,event(7,'started'));
assert.equal(view.error,null);assert.equal(view.text,'');
let b=reduceLive(undefined,{...event(8,'request',{request_id:'8',method:'item/tool/requestUserInput',params:{}}),id:'b'});
assert.equal(b.requests.length,1);assert.equal(view.requests.length,0);
b=reduceLive(b,{...event(9,'done',{error:null}),id:'b'});
assert.equal(b.requests.length,0);
console.log('PASS: state restoration, stale events, requests, item boundaries, failure recovery, independent threads');
view=reduceLive(view,event(10,'context',{used:1200,limit:10000}));
assert.equal(view.context[0],1200);assert.equal(view.busy,true);
view=reduceLive(view,event(11,'done',{error:null}));
view=reduceLive(view,event(12,'context',{used:400,limit:10000}));
assert.equal(view.busy,false,'Usage after compaction must not start a turn');
assert.equal(view.context[0],400,'Compaction may reduce context usage');
assert.equal(reduceLive(view,event(10,'context',{used:9000,limit:10000})),view);
view=reduceLive(view,event(13,'started'));
assert.equal(view.context[0],400,'Context survives the next turn until fresh usage arrives');
view=reduceLive(view,event(14,'context',{used:9000,limit:0}));
assert.equal(view.context[0],400,'Ignore invalid context windows');
assert.equal(b.context,undefined,'Usage must stay isolated by conversation');
console.log('PASS: live context, compaction, stale usage, invalid windows, thread isolation');
